# Generated by Django 3.1.5 on 2021-01-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.CharField(max_length=100, verbose_name='Introducción'),
        ),
    ]
