# Generated by Django 3.1.5 on 2021-01-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210123_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.company'),
        ),
    ]
